name: Deploy Jekyll Site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "_scripts/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for jekyll-github-metadata

      - name: Setup Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"  # Matches GitHub Pages' Ruby version
          bundler-cache: true
          cache-version: 2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            imagemagick \
            poppler-utils \
            libxml2-dev \
            libxslt1-dev
          # For jekyll-jupyter-notebook
          python3 -m pip install --upgrade pip
          python3 -m pip install nbconvert==6.5.4

      - name: Build Site with Plugins
        env:
          JEKYLL_ENV: production
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true  # For nokogiri performance
        run: |
          bundle config set force_ruby_platform true  # For platform-specific gems
          bundle install
          bundle exec jekyll build --trace --verbose

      - name: Optimize Assets
        run: |
          npm install -g purgecss@5.0.0 terser@5.26.0
          purgecss -c purgecss.config.js
          find _site -name "*.js" -exec terser {} -o {} \;
          find _site -name "*.html" -exec gzip -k {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
          keep_files: false
